---
title: "Report"
author: "Zachary Katz"
date: "2023-04-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(psych)
library(ggplot2)
library(reshape2)
library(GGally)
library(dplyr)
library(tidyr)
library(stringr)
library(scales)
library(glmnet)
```
Read in csv files:
```{r}
# Player, Year, Salary, Team
adjusted_nba_salaries <- read.csv("./data/adjusted_nba_salaries.csv")
# Team, Year, Total Salary
total_salary_by_team <- read.csv("./data/total_salary_by_team.csv")
# Team, Year, Wins
nba_team_wins <- read.csv("./data/nba_team_wins.csv")
# See Report advanced stats description
advanced_stats <- read.csv("./data/advanced_stats.csv")
# See Report advanced stats description
advanced_stats_2021 <- read.csv("./data/2021_advanced.csv")
# See Report shooting stats description
shooting_stats <- read.csv("./data/shooting_stats.csv")
# See Report shooting stats description
opponent_shooting_stats <- read.csv("./data/opponent_shooting_stats.csv")
# See Report total stats description
total_stats <- read.csv("./data/total_stats.csv")
# See Report total stats description
opponent_total_stats <- read.csv("./data/opponent_total_stats.csv")


# View(nba_salaries)
# View(nba_team_wins)
# View(advanced_stats)
# View(shooting_stats)
# View(opponent_shooting_stats)
# View(total_stats)
# View(opponent_total_stats)
```
Basic Summary
```{r}
print("==================================================")
print("NBA Salaries CSV")
# sapply(nba_salaries, summary)
describe(adjusted_nba_salaries)
print("==================================================")
print("NBA Total Salaries CSV")
# sapply(nba_salaries, summary)
describe(total_salary_by_team)
print("==================================================")
print("NBA Team Wins CSV")
# sapply(nba_team_wins, summary)
describe(nba_team_wins)
print("==================================================")
print("NBA Advanced Stats CSV")
# sapply(advanced_stats, summary)
describe(advanced_stats)
print("==================================================")
print("NBA Shooting Stats CSV")
# sapply(shooting_stats, summary)
describe(shooting_stats)
print("==================================================")
print("NBA Opponent Shooting Stats CSV")
# sapply(opponent_shooting_stats, summary)
describe(opponent_shooting_stats)
print("==================================================")
print("NBA Total Stats CSV")
# sapply(total_stats, summary)
describe(total_stats)
print("==================================================")
print("NBA Opponent Total Stats CSV")
# sapply(opponent_total_stats, summary)
describe(opponent_total_stats)
print("==================================================")
```
Basic Visualization (Correlation Matrices)
```{r}
# =========================================================
#				Correlation Matrices
# =========================================================
create_correlation_matrix <- function(data, name) {
	# Create correlation matrix
	numeric_data <- data[, sapply(data, is.numeric)]
	
	# Remove rows with missing values
	numeric_data <- numeric_data[complete.cases(numeric_data),]

	cor_mat <- cor(numeric_data)
	
	# Melt correlation matrix into long format for ggplot2
	cor_melt <- melt(cor_mat)
	
	# Create ggplot2 plot of correlation matrix
	ggplot(cor_melt, aes(x = Var1, y = Var2, fill = value)) +
	  geom_tile() +
	  scale_fill_gradient2(low = "blue", high = "red", mid = "white", midpoint = 0) +
	  theme_minimal() +
	  theme(axis.text.x = element_text(angle = 45, hjust = 1),
	        legend.title = element_blank()) +
	  labs(title = name)
}

create_correlation_matrix(total_stats, "Correlation Matrix of Total Statistics Variables")
create_correlation_matrix(opponent_total_stats, "Correlation Matrix of Opponent Total Statistics Variables")
create_correlation_matrix(advanced_stats, "Correlation Matrix of Advanced Statistics Variables")
create_correlation_matrix(shooting_stats, "Correlation Matrix of Shooting Statistics Variables")
create_correlation_matrix(opponent_shooting_stats, "Correlation Matrix of Opponent Shooting Statistics Variables")
```
Basic Visualization (Scatterplot Matrices)
```{r}
# =========================================================
#				ScatterPlot Matrices
# =========================================================
create_stat_to_wins <- function(stat) {
	stat$year <- as.integer(stat$year)
	merged_data <- left_join(stat, nba_team_wins, by = c("year", "team"))
	merged_data <- na.omit(merged_data)
	return(merged_data)
}

total_stats_wins <- create_stat_to_wins(total_stats)

# Relationship between wins and field goal attempts
ggpairs(total_stats_wins[,c("wins", "PTS", "FGA", "X3PA", "X2PA", "FTA")], title = "Scatterplot Matrix for Team Wins, Points Scored, and Shooting Percentages")
# Relationship between wins and field goal percentage
ggpairs(total_stats_wins[,c("wins", "PTS", "FGA", "X3P.", "X2P.", "FT.")], title = "Scatterplot Matrix for Team Wins, Points Scored, and Shooting Percentages")
# Relationship between wins and rebounds (*total rebounds*)
ggpairs(total_stats_wins[,c("wins", "PTS", "ORB", "DRB", "TRB")], title = "Scatterplot Matrix for Team Wins, Points Scored, and Shooting Percentages")
# Relationship between wins and assists, blocks, turnovers, personal fouls
ggpairs(total_stats_wins[,c("wins", "PTS", "AST", "BLK", "TOV", "PF")], title = "Scatterplot Matrix for Team Wins, Points Scored, and Shooting Percentages")
```
Basic Visualization (Boxplots)
```{r}
# =========================================================
#				Bubble Charts
# =========================================================
nba_total_salary_to_wins <- create_stat_to_wins(total_salary_by_team)

salary_wins_advanced <- left_join(advanced_stats, nba_total_salary_to_wins, by = c("year", "team"))
salary_wins_advanced <- na.omit(salary_wins_advanced)

salary_wins_advanced_total <- left_join(total_stats, nba_total_salary_to_wins, by = c("year", "team"))
salary_wins_advanced_total <- na.omit(salary_wins_advanced_total)

bubble_data <- data.frame(
  team_wins = salary_wins_advanced_total$wins,
  salary = salary_wins_advanced_total$total_salary,
  total_rebounds = salary_wins_advanced_total$TRB
)
ggplot(bubble_data, aes(x = salary, y = total_rebounds, size = team_wins, color = total_rebounds)) +
  geom_point() +
  scale_size_continuous(range = c(2, 10)) +
  labs(x = "Salary", y = "Total Rebounds", size = "Team Wins") + scale_color_gradient(low = "blue", high = "red")
```
Basic Visualization (Stacked Bar Plot)
```{r}
# =========================================================
#				Stacked Bar Plot
# =========================================================
# Creating a subset of total_stats dataframe for selected variables
team_stats <- total_stats[, c("team", "PTS", "AST", "TRB", "TOV")]

# Calculating the total of each variable by team
team_stats_summary <- aggregate(. ~ team, data = team_stats, FUN = sum)

# Converting data from wide to long format
team_stats_long <- gather(team_stats_summary, key = "stat", value = "total", -team)

# Creating the stacked bar chart
ggplot(team_stats_long, aes(x = team, y = total, fill = stat)) +
  geom_bar(stat = "identity") +
  ggtitle("Composition of Total Team Statistics") +
  xlab("Team") +
  ylab("Total") +
  theme_minimal() +
  theme(legend.position = "bottom")
```
Basic Analysis (Principal Component Analysis)
```{r}
nba_total_to_wins <- create_stat_to_wins(total_stats)

# Removing non-numeric columns
numeric_data <- nba_total_to_wins[, sapply(nba_total_to_wins, is.numeric)]

# Removing rows with missing values
numeric_data <- na.omit(numeric_data)

scaled_data <- scale(numeric_data)
pca <- prcomp(scaled_data, center = TRUE, scale. = TRUE)

# Extracting the first two principal components
pca_data <- data.frame(pca$x[,1:2])

# Extracting the loadings
loadings <- data.frame(pca$rotation[,1:2])

# Performing PCA on numeric data
pca <- prcomp(numeric_data, center = TRUE, scale. = TRUE)

# Extract the first two principal components and create a data frame
pca_data <- data.frame(pca$x[, 1:2], team = nba_total_to_wins$team)

# Extracting loadings and creating a data frame
loadings <- data.frame(variable = colnames(numeric_data), 
                       PC1 = pca$rotation[, 1], 
                       PC2 = pca$rotation[, 2])

# Plotting the loadings on the first two principal components
ggplot(pca_data, aes(x = PC1, y = PC2)) + 
  geom_point(aes(color = team)) + 
  geom_hline(yintercept = 0, linetype = "dashed") + 
  geom_vline(xintercept = 0, linetype = "dashed") + 
  geom_text(data = loadings, aes(x = PC1, y = PC2, label = variable), size = 3) +
  ggtitle("PCA: Loadings Plot")

```
Generating Model using LASSO selection on Advanced NBA Statistics
```{r}
add_wins_vector <- function(data) {
	data_to_wins <- left_join(data, nba_team_wins, by = c("year", "team"))
	data_to_wins <- na.omit(data_to_wins)
	return(data_to_wins)
}

generate_advanced_stats_model <- function(data, exclude, selection_type, title) {

	data_to_wins <- add_wins_vector(data)
  
	rsquared_vec <- c()
	rsquared_adj_vec <- c()

	cols <- ncol(data_to_wins)  
	column_iterator <- seq(from = 1, to = cols, by = 1)
  
	col_names_to_avoid <- exclude
	predictor_variables_df <- data_to_wins[!names(data_to_wins) %in% col_names_to_avoid]
	
	print("Number of Regressors:")	
	print(dim(predictor_variables_df)[2])

	print("LASSO Model for prediction of NBA team success based on NBA Advanced Stats")
	print("==================================================")
	print("Predictor Variables for LASSO model:")
	print(dim(predictor_variables_df))
	print(colnames(predictor_variables_df))
  
	wins_col_vector <- data_to_wins$wins

	print("==================================================")
	print("Response Variable for LASSO Model:")
	print(length(wins_col_vector))
	
	stopifnot(!any(is.na(predictor_variables_df)), !any(is.na(wins_col_vector)))
	model <- glmnet(x = data.matrix(predictor_variables_df), y = data.matrix(wins_col_vector), alpha = selection_type)
	num_cols <- dim(model$beta)[2]

	print("==================================================")
	print("Lambda Values tested by LASSO model:")
	print("---------------------------------------------------")
	print(model$lambda[num_cols])
	print("")
	print("Beta Values generated by LASSO model (best lambda):")
	print("---------------------------------------------------")
	print(model$beta[,num_cols])
	print("")
	print("LASSO model R-squared:")
	print("---------------------------------------------------")
	print(model$dev.ratio[num_cols])
	print("==================================================")
	
	# Creating a plot of the lambda values tested by the Lasso model
	plot(model$lambda, model$dev.ratio, type = "b", xlab = "Lambda", ylab = "Deviance Ratio", main = title)
	
	# Create a sample matrix
	beta_vals <- model$beta[,num_cols]
	barplot(beta_vals, col="blue", main="Lasso Model Beta Values", las=2)
	par(cex.axis=0.8, cex.main=1.0)
	
	return (model)
}

aparam <- c("Rk", "team", "W","L", "PW", "PL", "MOV", "Arena", "wins", "SRS", "ORtg", "DRtg", "NRtg", "TS.", "eFG..1", "eFG.", "FT.FGA")
aparam_min <- c("Rk", "team", "W","L", "PW", "PL", "MOV", "Arena", "wins", "ORtg", "NRtg", "TS.", "eFG..1", "eFG.")

advanced_stats_lasso_model <- generate_advanced_stats_model(advanced_stats, aparam, 1, "Lasso Model: Lambda vs. Deviance Ratio (AParam)")
advanced_stats_ridge_model <- generate_advanced_stats_model(advanced_stats, aparam, 0, "Ridge Model: Lambda vs. Deviance Ratio (AParam)")

advanced_stats_lasso_model_min <- generate_advanced_stats_model(advanced_stats, aparam_min, 1, "Lasso Model: Lambda vs. Deviance Ratio (Min AParams)")
advanced_stats_ridge_model_min <- generate_advanced_stats_model(advanced_stats, aparam_min, 0, "Ridge Model: Lambda vs. Deviance Ratio (Min AParams)")
```

```{r}
predict_team_success <- function(team, model, exclude, title) {
	advanced_stats_team <- advanced_stats[advanced_stats$team == team,]
	
	advanced_stats_team_wins <- add_wins_vector(advanced_stats_team)
	advanced_stats_team_wins_predictors <- advanced_stats_team_wins[!names(advanced_stats_team_wins) %in% exclude]

	num_cols <- dim(model$beta)[2]
	best_lambda_value <- model$lambda[num_cols]
	
	print("Number of Regressors:")
	print(dim(advanced_stats_team_wins_predictors)[2])
	
	results <- predict(model, newx=data.matrix(advanced_stats_team_wins_predictors), s=best_lambda_value, type="response")
	
	plot(advanced_stats_team_wins$year, results, col = "red", xlab = "Year", ylab = cat("Wins for ", team, ""), main=title)
	points(advanced_stats_team_wins$year, advanced_stats_team_wins$wins, col = "grey")
	legend("topright", legend = c("Predicted wins", "Actual Wins"), col = c("grey", "green"), pch=1)
	
	return(results)
}

results_lasso <- predict_team_success("houston rockets", advanced_stats_lasso_model, aparam, "Lasso AParams")
results_ridge <- predict_team_success("houston rockets", advanced_stats_ridge_model, aparam, "Ridge AParams")

results_lasso_min <- predict_team_success("houston rockets", advanced_stats_lasso_model_min, aparam_min, "Lasso Min AParams")
results_ridge_min <- predict_team_success("houston rockets", advanced_stats_ridge_model_min, aparam_min, "Ridge Min AParams")

```
Applying our model to future data
```{r}
predict_on_future_data <- function(future_data, model, exclude, title) {
	future_data_predictors <- future_data[!names(future_data) %in% exclude]
	
	year_str <- future_data$year[1]

	num_cols <- dim(model$beta)[2]
	best_lambda_value <- model$lambda[num_cols]
	
	print("Number of Regressors:")
	print(dim(future_data_predictors)[2])
	
	new_year_string <- paste("Wins for Teams in", year_str)
	
	results <- predict(model, newx=data.matrix(future_data_predictors), s=best_lambda_value, type="response")
	
	team_inds <- seq(from=1, to=length(future_data$team), by=1)
	plot(team_inds, results, col = "red", xlab = "Team", ylab = new_year_string, ylim=c(10, 90), main=title)
	# text(seq_along(future_data$team), rep(0, length(future_data$team)), labels = future_data$team, srt = 90, adj = c(0, 0.5), xpd = TRUE, cex = 0.8)
	points(team_inds, future_data$W, col = "grey")
	legend("topright", legend = c("Predicted wins", "Actual Wins"), col = c("red", "grey"), pch=1)
	
	return(results)
}

result_future_lasso <- predict_on_future_data(advanced_stats_2021, advanced_stats_lasso_model, aparam, "Lasso AParam Prediction on Future Data")
result_future_lasso
result_future_ridge <- predict_on_future_data(advanced_stats_2021, advanced_stats_ridge_model, aparam, "Ridge AParam Prediction on Future Data")
result_future_lasso_min <- predict_on_future_data(advanced_stats_2021, advanced_stats_lasso_model_min, aparam_min, "Lasso Min AParam Prediction on Future Data")
result_future_ridge_min <- predict_on_future_data(advanced_stats_2021, advanced_stats_ridge_model_min, aparam_min, "Ridge Min AParam Prediction on Future Data")

```